### ISSUE TITLE
Huobi is not working

### ISSUE THREAD

**Issue by gavincyi** [gavincyi/BitcoinExchangeFH#18]
Due to the socketIO-client

**Comment by jpspfaria** [comment]
Hi @gavincyi , first of all thanks for sharing this code, very good work!

Is this the error you are talking about?

Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/socketIO_client/transports.py", line 174, in recv
    yield self._connection.recv()
  File "/usr/local/lib/python3.5/dist-packages/websocket/_core.py", line 293, in recv
    opcode, data = self.recv_data()
  File "/usr/local/lib/python3.5/dist-packages/websocket/_core.py", line 310, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/local/lib/python3.5/dist-packages/websocket/_core.py", line 323, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/local/lib/python3.5/dist-packages/websocket/_core.py", line 357, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/local/lib/python3.5/dist-packages/websocket/_abnf.py", line 336, in recv_frame
    self.recv_header()
  File "/usr/local/lib/python3.5/dist-packages/websocket/_abnf.py", line 286, in recv_header
    header = self.recv_strict(2)
  File "/usr/local/lib/python3.5/dist-packages/websocket/_abnf.py", line 371, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/usr/local/lib/python3.5/dist-packages/websocket/_core.py", line 427, in _recv
    return recv(self.sock, bufsize)
  File "/usr/local/lib/python3.5/dist-packages/websocket/_socket.py", line 93, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/befh/ws_api_socket2.py", line 54, in <lambda>
    self.wst = threading.Thread(target=lambda: self.run(url, 80))
  File "/usr/local/lib/python3.5/dist-packages/befh/ws_api_socket2.py", line 66, in run
    self.ws.wait(1)
  File "/usr/local/lib/python3.5/dist-packages/socketIO_client/__init__.py", line 252, in wait
    self._process_events(timeout)
  File "/usr/local/lib/python3.5/dist-packages/socketIO_client/__init__.py", line 269, in _process_events
    for packet in self._transport.recv_packet(timeout):
  File "/usr/local/lib/python3.5/dist-packages/socketIO_client/transports.py", line 98, in recv_packet
    for packet_text in self.recv(timeout=timeout):
  File "/usr/local/lib/python3.5/dist-packages/socketIO_client/transports.py", line 177, in recv
    except websocket.SSLError as e:
AttributeError: module 'websocket' has no attribute 'SSLError'

**Comment by gavincyi** [comment]
Yes correct. The issue is still opened as the protocol requires a lower socketIO version. I am still looking for a solution.
